# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CroidCoins

on:
  push:
    branches: [ "master" ]
  pull_request:
    paths: /**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
    - env:
        ETH_ACCOUNT_PHRASE: ${{ secrets.ETH_ACCOUNT_PHRASE }}
        RINKEBY_DEPLOY_NETWORK: ${{ secrets.RINKEBY_DEPLOY_NETWORK }}
        NEXT_PUBLIC_RINKEBY_DEPLOY_NETWORK: ${{ secrets.NEXT_PUBLIC_RINKEBY_DEPLOY_NETWORK }}
        
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn run build --if-present
    - run: yarn test
